services:
  tuya-exporter:
    image: tuyamon:latest
    ports:
       - 8757:8757
    volumes:
      #- ./tinytuya.json:/app/tinytuya.json # either this or devices.json
      - ./devices.json:/app/devices.json
    restart: always
